-- MySQL 5.7
-- 百度智能外呼：结构化分析表（便于后续 AI 总结 / 查询统计）

CREATE TABLE IF NOT EXISTS `baidu_call_facts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `callback_type` TINYINT NOT NULL,
  `session_id` VARCHAR(128) NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `task_id` VARCHAR(64) NOT NULL DEFAULT '',
  `task_name` VARCHAR(255) NOT NULL DEFAULT '',
  `robot_id` VARCHAR(64) NOT NULL DEFAULT '',
  `robot_name` VARCHAR(255) NOT NULL DEFAULT '',
  `member_id` BIGINT NOT NULL,
  `mobile` VARCHAR(64) NOT NULL DEFAULT '',
  `caller_num` VARCHAR(64) NOT NULL DEFAULT '',
  `end_type` INT NOT NULL,
  `end_type_reason` VARCHAR(64) NOT NULL DEFAULT '',
  `sip_code` VARCHAR(32) NOT NULL DEFAULT '',
  `sip_info` VARCHAR(255) NOT NULL DEFAULT '',
  `intent` VARCHAR(255) NOT NULL DEFAULT '',
  `call_times` INT NULL,
  `call_type` INT NULL,
  `duration_time_len` INT NULL,
  `ringing_time_len` INT NULL,
  `talking_time_len` INT NULL,
  `robot_talking_time_len` INT NULL,
  `start_time` DATETIME(3) NULL,
  `ring_start_time` DATETIME(3) NULL,
  `talking_start_time` DATETIME(3) NULL,
  `end_time` DATETIME(3) NULL,
  `received_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session` (`session_id`),
  KEY `idx_member` (`member_id`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_task_member` (`task_id`, `member_id`),
  KEY `idx_received_at` (`received_at`),
  KEY `idx_start_time` (`start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `baidu_call_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `session_id` VARCHAR(128) NOT NULL,
  `record_index` INT NOT NULL,
  `role` VARCHAR(32) NOT NULL DEFAULT '',
  `timestamp_us` BIGINT NULL,
  `context_text` TEXT NULL,
  `content` TEXT NULL,
  `intent` VARCHAR(255) NOT NULL DEFAULT '',
  `start` VARCHAR(32) NOT NULL DEFAULT '',
  `stop` VARCHAR(32) NOT NULL DEFAULT '',
  `time_len_ms` BIGINT NULL,
  `interrupted` TINYINT(1) NULL,
  `interrupted_time` VARCHAR(32) NOT NULL DEFAULT '',
  `silent` TINYINT(1) NULL,
  `sn` VARCHAR(128) NOT NULL DEFAULT '',
  `node_info` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_record` (`session_id`, `record_index`),
  KEY `idx_session_role` (`session_id`, `role`),
  KEY `idx_timestamp_us` (`timestamp_us`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

